local T, C, L = unpack(Tukui)
if not C.misc.uibuttons == true then return end


local function CreateUIButton(name, parent, text)
	local b = CreateFrame("Button", name, parent, "SecureActionButtonTemplate")
	b:Size (70, 13)
	b:StripTextures(true)
	b:SetTemplate("Default")
	b:SetBackdropColor(.06,.06,.06, .7)
	b:EnableMouse(true)
	b:RegisterForClicks("AnyUp")
	
	b:HookScript("OnEnter", function(self)
		self:SetBackdropBorderColor(148/255, 130/255, 201/255, 1)
	end)
	b:HookScript("OnLeave", function(self)
		self:SetBackdropBorderColor(.06,.06,.06)
	end)
	
	b:FontString(nil, C.media.pixelfont, 8, "MONOCHROMEOUTLINE")
	b.text:SetText(text)
	b.text:SetPoint("CENTER", b)
end

CreateUIButton("KacaosUI_Config_Button", UIParent, "Config")
KacaosUI_Config_Button:SetAttribute("type1", "macro")
KacaosUI_Config_Button:SetAttribute("macrotext1", "/tukui")
KacaosUI_Config_Button.text:SetFont(C.media.pixelfont, 8, "MONOCHROMEOUTLINE")
KacaosUI_Config_Button.text:SetShadowOffset(0,0)
KacaosUI_Config_Button:Point("RIGHT", Minimap, "LEFT", -5, -39)
KacaosUI_Config_Button:SetFrameLevel(3)
KacaosUI_Config_Button:EnableMouse(true)
KacaosUI_Config_Button:HookScript("OnEnter", function(self)
          GameTooltip:SetOwner(self, "ANCHOR_TOPRIGHT", -75, 3)
		  GameTooltip:AddLine("ConfigUi", .6, .6, .6, .6, .6, 1)
          GameTooltip:AddLine("Click to open the ingame config for tukui", 1, 1, 1, 1, 1, 1)
          GameTooltip:Show()
        end)
KacaosUI_Config_Button:HookScript("OnLeave", function(self) GameTooltip:Hide() end)
RegisterStateDriver(KacaosUI_Config_Button, "visibility", "[petbattle] hide; show")

CreateUIButton("KacaosUI_MoveUI_Button", UIParent, "MoveUi")
KacaosUI_MoveUI_Button:SetAttribute("type1", "macro")
KacaosUI_MoveUI_Button:SetAttribute("macrotext1", "/moveui")
KacaosUI_MoveUI_Button.text:SetFont(C.media.pixelfont, 8, "MONOCHROMEOUTLINE")
KacaosUI_MoveUI_Button.text:SetShadowOffset(0,0)
KacaosUI_MoveUI_Button:Point("RIGHT", Minimap, "LEFT", -5, -24)
KacaosUI_MoveUI_Button:EnableMouse(true)
KacaosUI_MoveUI_Button:HookScript("OnEnter", function(self)
          GameTooltip:SetOwner(self, "ANCHOR_TOPRIGHT", -75, -4)
          GameTooltip:AddLine("MoveUi", .6, .6, .6, .6, .6, 1)
          GameTooltip:AddLine("Click to toggle move some elements", 1, 1, 1, 1, 1, 1)
          GameTooltip:Show()
        end)
KacaosUI_MoveUI_Button:HookScript("OnLeave", function(self) GameTooltip:Hide() end)
RegisterStateDriver(KacaosUI_MoveUI_Button, "visibility", "[petbattle] hide; show")

CreateUIButton("KacaosUI_stam_Button", UIParent, "AddOns")
KacaosUI_stam_Button:SetAttribute("type1", "macro")
KacaosUI_stam_Button:SetAttribute("macrotext1", "/am")
KacaosUI_stam_Button.text:SetFont(C.media.pixelfont, 8, "MONOCHROMEOUTLINE")
KacaosUI_stam_Button.text:SetShadowOffset(0,0)
KacaosUI_stam_Button:Point("RIGHT", Minimap, "LEFT", -5, -9)
KacaosUI_stam_Button:EnableMouse(true)
KacaosUI_stam_Button:HookScript("OnEnter", function(self)
          GameTooltip:SetOwner(self, "ANCHOR_TOPRIGHT", -75, -9)
          GameTooltip:AddLine("AddonManager", .6, .6, .6, .6, .6, 1)
          GameTooltip:AddLine("Click to open AddonManager", 1, 1, 1, 1, 1, 1)
          GameTooltip:Show()
        end)
KacaosUI_stam_Button:HookScript("OnLeave", function(self) GameTooltip:Hide() end)
RegisterStateDriver(KacaosUI_stam_Button, "visibility", "[petbattle] hide; show")

CreateUIButton("KacaosUI_rl_Button", UIParent, "Reload")
KacaosUI_rl_Button:Size(70, 13)
KacaosUI_rl_Button:SetAttribute("type1", "macro")
KacaosUI_rl_Button:SetAttribute("macrotext1", "/rl")
KacaosUI_rl_Button.text:SetFont(C.media.pixelfont, 8, "MONOCHROMEOUTLINE")
KacaosUI_rl_Button.text:SetShadowOffset(0,0)
KacaosUI_rl_Button:Point("RIGHT", Minimap, "LEFT", -5, 6)
KacaosUI_rl_Button:EnableMouse(true)
KacaosUI_rl_Button:HookScript("OnEnter", function(self)
          GameTooltip:SetOwner(self, "ANCHOR_TOPRIGHT", -75, -18)
          GameTooltip:AddLine("ReloadUI", .6, .6, .6, .6, .6, 1)
          GameTooltip:AddLine("Click to ReloadUI", 1, 1, 1, 1, 1, 1)
          GameTooltip:Show()
        end)
KacaosUI_rl_Button:HookScript("OnLeave", function(self) GameTooltip:Hide() end)
RegisterStateDriver(KacaosUI_rl_Button, "visibility", "[petbattle] hide; show")

CreateUIButton("KacaosUI_tb_Button", UIParent, "Testui")
KacaosUI_tb_Button:Size(70, 13)
KacaosUI_tb_Button:SetAttribute("type1", "macro")
KacaosUI_tb_Button:SetAttribute("macrotext1", "/testui boss")
KacaosUI_tb_Button.text:SetFont(C.media.pixelfont, 8, "MONOCHROMEOUTLINE")
KacaosUI_tb_Button.text:SetShadowOffset(0,0)
KacaosUI_tb_Button:Point("RIGHT", Minimap, "LEFT", -5, 21)
KacaosUI_tb_Button:EnableMouse(true)
KacaosUI_tb_Button:HookScript("OnEnter", function(self)
          GameTooltip:SetOwner(self, "ANCHOR_TOPRIGHT", -75, -25)
          GameTooltip:AddLine("TestUI Boss", .6, .6, .6, .6, .6, 1)
          GameTooltip:AddLine("Click to toggle Bossframes (only testmodus)", 1, 1, 1, 1, 1, 1)
          GameTooltip:Show()
        end)
KacaosUI_tb_Button:HookScript("OnLeave", function(self) GameTooltip:Hide() end)
RegisterStateDriver(KacaosUI_tb_Button, "visibility", "[petbattle] hide; show")

CreateUIButton("KacaosUI_help_Button", UIParent, "Help")
KacaosUI_help_Button:Size(70, 13)
KacaosUI_help_Button:SetAttribute("type1", "macro")
KacaosUI_help_Button:SetAttribute("macrotext1", "/kuihelp")
KacaosUI_help_Button.text:SetFont(C.media.pixelfont, 8, "MONOCHROMEOUTLINE")
KacaosUI_help_Button.text:SetShadowOffset(0,0)
KacaosUI_help_Button:Point("RIGHT", Minimap, "LEFT", -5, 51)
KacaosUI_help_Button:EnableMouse(true)
KacaosUI_help_Button:HookScript("OnEnter", function(self)
          GameTooltip:SetOwner(self, "ANCHOR_TOPRIGHT", -75, -25)
          GameTooltip:AddLine("Help", .6, .6, .6, .6, .6, 1)
          GameTooltip:AddLine("Toggle Helpframe window", 1, 1, 1, 1, 1, 1)
          GameTooltip:Show()
        end)
KacaosUI_help_Button:HookScript("OnLeave", function(self) GameTooltip:Hide() end)
RegisterStateDriver(KacaosUI_help_Button, "visibility", "[petbattle] hide; show")

CreateUIButton("KacaosUI_rdebuff_Button", UIParent, "Debuffs")
KacaosUI_rdebuff_Button:Size(70, 13)
KacaosUI_rdebuff_Button:SetAttribute("type1", "macro")
KacaosUI_rdebuff_Button:SetAttribute("macrotext1", "/debuffs")
KacaosUI_rdebuff_Button.text:SetFont(C.media.pixelfont, 8, "MONOCHROMEOUTLINE")
KacaosUI_rdebuff_Button.text:SetShadowOffset(0,0)
KacaosUI_rdebuff_Button:Point("RIGHT", Minimap, "LEFT", -5, 36)
KacaosUI_rdebuff_Button:EnableMouse(true)
KacaosUI_rdebuff_Button:HookScript("OnEnter", function(self)
          GameTooltip:SetOwner(self, "ANCHOR_TOPRIGHT", -75, -25)
          GameTooltip:AddLine("raidDebuffs", .6, .6, .6, .6, .6, 1)
          GameTooltip:AddLine("Toggle Raiddebuff window (To edit debuffs to your grid)", 1, 1, 1, 1, 1, 1)
          GameTooltip:Show()
        end)
KacaosUI_rdebuff_Button:HookScript("OnLeave", function(self) GameTooltip:Hide() end)
RegisterStateDriver(KacaosUI_rdebuff_Button, "visibility", "[petbattle] hide; show")


-- fade out infight
local fadeout = CreateFrame("Frame")
fadeout:RegisterEvent("PLAYER_ENTERING_WORLD")
fadeout:RegisterEvent("PLAYER_REGEN_ENABLED")
fadeout:RegisterEvent("PLAYER_REGEN_DISABLED")
fadeout:SetScript("OnEvent", function(self, event)
	if event == "PLAYER_REGEN_ENABLED" then
			KacaosUI_Config_Button:Show()
			KacaosUI_MoveUI_Button:Show()
			KacaosUI_stam_Button:Show()
			KacaosUI_rl_Button:Show()
			KacaosUI_tb_Button:Show()
			KacaosUI_help_Button:Show()
			KacaosUI_rdebuff_Button:Show()
	elseif event == "PLAYER_REGEN_DISABLED" then
			KacaosUI_Config_Button:Hide()
			KacaosUI_MoveUI_Button:Hide()
			KacaosUI_stam_Button:Hide()
			KacaosUI_rl_Button:Hide()
			KacaosUI_tb_Button:Hide()
			KacaosUI_help_Button:Hide()
			KacaosUI_rdebuff_Button:Hide()
	end
end)
